sudo: false
dist: trusty
language: bash

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - bats

before_script:
  - bash test/bin/install-wp-tests.sh wordpress_test root '' localhost latest

script:
  - bats test
